application: terminally-incoherent-forum
version: 2
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /img
  static_dir: img

- url: .*
  script: main.py

